server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

outbound:
  identity:
    client-id:
    client-secret:
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "8ryuZaIPL7kxEnuq6G6IZWkosIVlCr1FNji9mAJR8MKrJG6UfOOmgiGTjlkm5/Ty"
  valid-duration: 1200 # in second
  refreshable-duration: 2400 # in second